name: Deploy Frontend WhatsApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build e push da imagem
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL="https://whatsapp.back.renannardi.com" \
            -t devnardi/web-whatsapp:latest .
          docker push devnardi/web-whatsapp:latest

      - name: Subindo novo container
        run: |
          docker rm -f web-whatsapp || true
          docker pull devnardi/web-whatsapp:latest
          docker run -d \
            --name web-whatsapp \
            -p 3030:3000 \
            --network n8n_net \
            devnardi/web-whatsapp:latest
